Weblog/Weblog/Models/ArticleModel.cs
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Web;

namespace Weblog.Models
{
    public class ArticleModel
    {
        public ArticleModel()
        {
            Title = "динамический заголовок";
            Body = "<p> динамический текст</p>";
            Date = DateTime.Now;
            Comments = new Collection<CommentItemModel>();
        }
        public string Title { get; set; }
        public string Body { get; set; }
        public DateTime Date { get; set; }
        public ICollection<CommentItemModel> Comments { get; set; }
    }
}

Weblog/Weblog/Models/CommentItemModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Weblog.Models
{
    public class CommentItemModel
    { public CommentItemModel()
        {
            UserName = "динамич имя";
            Body = "Динам Ком";
            Date = DateTime.Now;
        }
        public string UserName { get; set; }
        public string Body { get; set; }
        public DateTime Date { get; set; }
    }
}

Weblog/Weblog/Models/ResentDateItemModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Weblog.Models
{
    public class ResentDateItemModel
    {
        public ResentDateItemModel()
        {
            text = "text";
            URL = "http://yandex.ru";
            Date = DateTime.Now.AddDays(-1);

        }
        public string text { get; set; }
        public string URL { get; set; }
        public DateTime Date { get; set; }
    }
}

Weblog/Weblog/Models/ResentDateModel.cs
using System;
using System.Collections.ObjectModel;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Weblog.Models
{
    public class ResentDateModel
    {
        public ResentDateModel ()
        {
            Items = new Collection<ResentDateItemModel>();
            Items.Add(new ResentDateItemModel () );
            Items.Add(new ResentDateItemModel());
            Items.Add(new ResentDateItemModel());
        }
        public ICollection<ResentDateItemModel> Items { get; set; }
    }
} 

Weblog/Weblog/Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Weblog.Controllers
{
    public class CommentController : Controller
    {
        // GET: Comment
        public ActionResult Resent()
        {
            var model = new Models.ResentDateModel();
            return View(model);
        }
    }
}

Weblog/Weblog/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Weblog.Models;

namespace Weblog.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            var model = new ArticleModel();
           
            return View(model);
        }
    }
}

Weblog/Weblog/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Weblog.Controllers
{
    public class PostController : Controller
    {
        // GET: Comment
        public ActionResult Resent()
        {
            var model = new Models.ResentDateModel();
            return View(model);
        }
    }
}

Weblog/Weblog/Views/Comment/Resent.cshtml
@{
    Layout = null;
}
@model Weblog.Models.ResentDateModel
<div class="post-wrap">
<h3>resent comments</h3>
<ul>
    @foreach (var item in Model.Items)
    {
        <li>
            <p class="date">@item.Date.ToString("D")<span>@item.Date.ToString("hh:mm")</span></p>
            <p class="post"><a href="@item.URL">@item.text</a></p>
        </li>
    }
</ul>
</div>

Weblog/Weblog/Views/Home/Index.cshtml
@model Weblog.Models.ArticleModel
<div class="wrap-article">
    <h2>@Model.Title</h2>
    <p class="date"><span>@Model.Date.ToString("D")</span> <span>@Model.Date.ToString("hh:mm")</span></p>
    <div class="text-block">
        @Html.Raw(Model.Body)
    </div>
</div>
<div class="wrap-comment">
    <h2>Коментарии</h2>
    <ul class="list-comm">
        @foreach (var item in Model.Comments)
        {
            <li>
                <div class="avatar"><img src="~/contents/images/ava-com.png" alt=""></div>
                <div class="comment-text">
                    <a href="#">@item.UserName</a>
                    <p class="date"><span>@item.Date.ToString("D")</span> <span>@item.Date.ToString("hh:mm")</span></p>
                    <p>@item.Body</p>
                </div>
            </li>
        }


    </ul>
</div>
<div class="add-comment">
    <textarea name="" placeholder="ваш комент" class="txt-area"></textarea>
    <div class="wrap-btn">
        <button class="btn-save">сохранить</button>
        <button class="btn-cansel">отмена</button>
    </div>
</div>

Weblog/Weblog/Views/Post/Resent.cshtml
@{
    Layout = null;
}
@model Weblog.Models.ResentDateModel
<div class="post-wrap">
    <h3>resent post</h3>
    <ul>
        @foreach (var item in Model.Items)
        {
            <li>
                <p class="date">@item.Date.ToString("D")</p>
                <p class="post"><a href="@item.URL">@item.text</a></p>
            </li>
        }
    </ul>
</div>

Weblog/Weblog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="~/contents/css/reset.css">
    <link rel="stylesheet" href="~/contents/css/style.css">
    <
    <style>
        body {
            background: #333; /* Цвет фона */
        }
    </style>
</head>
<body>

    <div class="wrap">
        <div class="up-col">

            <div class="slidebar1">
                <div class="search-form">
                    <h3>найти</h3>
                    <input type="search">
                </div>
                <div class="wrap-avatar">
                    <img src="~/contents/images/avatar.png" alt="">
                    <h2>Блог Тимошенко</h2>
                </div>
            </div>
            <div class="slidebar2">
                <p>добро пожаловать <a href="#">Регистрация / Вход </a></p>
                <div class="text-av"><h3>Тут текст об этом блоге</h3></div>
                <div class="menu">
                    <ul>
                        <li><a href="#">Home</a></li>
                        <li><a href="#">Archive</a></li>
                        <li><a href="#">Aboute me</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="left-col">
            @RenderBody()
        </div>
        <div class="righ-col">
            @Html.Action("Resent", "Post")
            @Html.Action("Resent","Comment") 
        </div>
    </div>
</body>
</html>